import React from 'react';

type BadgeType = 
  | 'AI_ANALYSIS' 
  | 'GENERATED_BY_GEMINI' 
  | 'DOCUMENT_GROUNDED' 
  | 'AI_COMPARISON'
  | 'HIGH_RISK'
  | 'MEDIUM_RISK'
  | 'LOW_RISK'
  | 'STATUS_UPLOADED'
  | 'STATUS_EXTRACTING'
  | 'STATUS_CHUNKING'
  | 'STATUS_EMBEDDING'
  | 'STATUS_READY'
  | 'STATUS_ANALYZING'
  | 'STATUS_COMPLETED'
  | 'STATUS_FAILED';

interface BadgeProps {
  type: BadgeType;
  customText?: string;
  size?: 'sm' | 'md';
}

export function Badge({ type, customText, size = 'sm' }: BadgeProps) {
  const sizeClasses = size === 'sm' ? 'px-2 py-0.5 text-[11px]' : 'px-2.5 py-1 text-xs';

  switch (type) {
    case 'AI_ANALYSIS':
      return (
        <span className={`inline-flex items-center font-bold tracking-wider uppercase rounded bg-slate-900 text-blue-300 border border-slate-700 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-blue-400 mr-1.5 animate-pulse"></span>
          AI ANALYSIS
        </span>
      );

    case 'GENERATED_BY_GEMINI':
      return (
        <span className={`inline-flex items-center font-semibold tracking-wider uppercase rounded bg-purple-950/80 text-purple-300 border border-purple-800/60 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-purple-400 mr-1.5"></span>
          GENERATED BY GEMINI
        </span>
      );

    case 'DOCUMENT_GROUNDED':
      return (
        <span className={`inline-flex items-center font-semibold tracking-wider uppercase rounded bg-emerald-950/80 text-emerald-300 border border-emerald-800/60 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mr-1.5"></span>
          DOCUMENT-GROUNDED ANSWER
        </span>
      );

    case 'AI_COMPARISON':
      return (
        <span className={`inline-flex items-center font-semibold tracking-wider uppercase rounded bg-indigo-950/80 text-indigo-300 border border-indigo-800/60 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mr-1.5"></span>
          AI COMPARISON
        </span>
      );

    case 'HIGH_RISK':
      return (
        <span className={`inline-flex items-center font-semibold rounded bg-rose-100 text-rose-800 border border-rose-200 ${sizeClasses}`}>
          High Review Need
        </span>
      );

    case 'MEDIUM_RISK':
      return (
        <span className={`inline-flex items-center font-semibold rounded bg-amber-100 text-amber-800 border border-amber-200 ${sizeClasses}`}>
          Moderate Review
        </span>
      );

    case 'LOW_RISK':
      return (
        <span className={`inline-flex items-center font-semibold rounded bg-slate-100 text-slate-700 border border-slate-200 ${sizeClasses}`}>
          Standard Provision
        </span>
      );

    case 'STATUS_UPLOADED':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-blue-50 text-blue-700 border border-blue-200 ${sizeClasses}`}>
          Uploaded
        </span>
      );

    case 'STATUS_EXTRACTING':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-indigo-50 text-indigo-700 border border-indigo-200 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 mr-1.5 animate-pulse"></span>
          Extracting...
        </span>
      );

    case 'STATUS_CHUNKING':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-purple-50 text-purple-700 border border-purple-200 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mr-1.5 animate-pulse"></span>
          Chunking...
        </span>
      );

    case 'STATUS_EMBEDDING':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-cyan-50 text-cyan-700 border border-cyan-200 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-cyan-500 mr-1.5 animate-pulse"></span>
          Embedding...
        </span>
      );

    case 'STATUS_READY':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mr-1.5"></span>
          Ready
        </span>
      );

    case 'STATUS_ANALYZING':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-amber-50 text-amber-700 border border-amber-200 ${sizeClasses}`}>
          <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mr-1.5 animate-spin"></span>
          Analyzing...
        </span>
      );

    case 'STATUS_COMPLETED':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-emerald-100 text-emerald-800 border border-emerald-300 ${sizeClasses}`}>
          Completed
        </span>
      );

    case 'STATUS_FAILED':
      return (
        <span className={`inline-flex items-center font-medium rounded-full bg-red-50 text-red-700 border border-red-200 ${sizeClasses}`}>
          Failed
        </span>
      );

    default:
      return (
        <span className={`inline-flex items-center rounded bg-slate-100 text-slate-800 ${sizeClasses}`}>
          {customText || type}
        </span>
      );
  }
}
